language: android
sudo: false
jdk:
    - oraclejdk8
env:
    global:
      - ANDROID_TOOLS=${ANDROID_HOME}/tools

      - AUTHOR_NAME='Louisa Derrick'
      - AUTHOR_EMAIL='dhdsuwnx@gmail.com'
      - BRANCH_KEY=''
      - BRANCH_URI_SCHEME='goldslot'
      - BRANCH_LINK='zvg6.app.link'
      - IOS_VALUE='GV574NJ3RK'
      - WIDGET_ID='com.goldslotst.goldcasino'
      - WIDGET_VER='1.0'
      - APP_NAME='казино'
      - APP_DESCRIPTION='Гора монет и бонусов'

      - FIREBASE_SENDER_ID=''
      - IONIC_APP_ID=''
      - MAIN_DOMAIN='http://d.trkslotsapp.club'
      - APP_ID='1165'

      - IONIC_EMAIL='28463842@etlgr.com'
      - IONIC_PASS='od7tcU4+jaz'
      - CODROVA_ANDROID_VER='7.0.0'
      - CORDOVA_PLUGIN_INAPPBROWSER_VER='1.7.2'
      - CORDOVA_PLUGIN_BRANCH_SDK_VER='2.4.0'
      - CORDOVA_PLUGIN_PUSH_VER='1.10.5'
      - CORDOVA_ADDITIONAL_PLUGINS='https://github.com/amritk/cordova-plugin-facebook4  --save --variable APP_ID=328255904324569 --variable APP_NAME=goldslot cordova-plugin-camera cordova-plugin-media-capture cordova-plugin-contacts'

      - KEYPASS='bais7d612lkjasd'
      - CERT_INFO='CN=,OU=,O=,L=,ST=,C='
addons:
  apt:
    packages:
    - xmlstarlet
before_install:
    - nvm install 6
    # ensure at least gradle 3.3 is in place.
    - wget http://services.gradle.org/distributions/gradle-3.3-bin.zip
    - unzip gradle-3.3-bin.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=${GRADLE_HOME}/bin:${ANDROID_HOME}:${ANDROID_HOME}/emulator:${ANDROID_TOOLS}:${ANDROID_TOOLS}/bin:${ANDROID_HOME}/platform-tools:$PATH
    - node --version
    - gradle --version
    - echo y | android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-26.0.2,android-26,android-25,extra-google-m2repository,extra-android-m2repository
android:
    components:
      - tools
install:
    - npm install -g gulp bower cordova ionic
    - npm install
    - bower update
notifications:
  email:
    - 28463842@etlgr.com
deploy:
  provider: releases
  api_key:
    secure: 3iWscwbxw5SYJdqzHTUbrS8LCp2EQklq0BXlWpC1JCanHWYQfGWJfxn7XP2FGRdEZKLiZMTl1L4nMwUvwnxVLjbgDCYRj0LBM05pCfVbUP0Tge++ZfozpOGagRgZvK5iXW+iybaf5JpR+VmG80Eo8ZrP1Q48WRR9s2c9LYTGgkB/3yQC2A4RJnPe0ZgBHFj31ExCLES7OZ3U1Xq7Glz7cvbguZA/DvG7GugHg0PDlJjromPNRwBKdXSZ2GWGlegjMXXgMx15kRO3jCuc2ho+6WvP1W7HFXT2ovgnX8OcB5ycUMvNUBYOpvtDzsn0FTD2+ieFCfBhaCnPIcpFDZ+LFhgbdY8NgDgwT8V6OFpg6TKOinYqhIFxN+PqWuelH2HiHlE9kjZkXrEFnN1Iqau7BwiZ0JYiRQXitINnmm3eU49MFGelZUjhEfdIzn4H4QHqUw2I/cgO3Oq/LRIplfZeM1i0RVF2szqhwfcyOggSDUKGrCQ9oBvnWu9hzZ9wACZq3JfKP16JPHXaYaDGEf9T4VSds0yZY0PKDCeMGdkY4nMvebNzFVeOaGOPrrvhs+ZI1vHXtbm/h3cKiI6uXI/ZO+nV5PIKuw/OwyyLdWrdMsIGBQc7Rfhz8qGR0EWBONvltUKOHtAL48OUo1whoH6Q/PpmyMRO7jOXU0aH7CnO+1s=
  file:
    - myapp/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
    #- myapp/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk ../release_app/release_app*
  on:
    repo: bastardapp/travis
  skip_cleanup: true
after_script:
    - codecov
script:
    - ./travis.sh
